data_1.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 10
  subtaskId: 0
data_2.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 10
  subtaskId: 0
data_3.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 20
  subtaskId: 1
data_4.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 20
  subtaskId: 1
data_5.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 20
  subtaskId: 1
data_6.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 5
  subtaskId: 2
data_7.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 5
  subtaskId: 2
data_8.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 15
  subtaskId: 3
data_9.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 15
  subtaskId: 3
data_10.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 15
  subtaskId: 3
data_11.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 20
  subtaskId: 4
data_12.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 20
  subtaskId: 4
data_13.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 20
  subtaskId: 4
data_14.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 30
  subtaskId: 5
data_15.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 30
  subtaskId: 5
data_16.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 30
  subtaskId: 5
data_17.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 30
  subtaskId: 5
data_18.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 30
  subtaskId: 5
data_19.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 30
  subtaskId: 5
data_20.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 30
  subtaskId: 5
data_21.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 30
  subtaskId: 5
data_22.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 30
  subtaskId: 5
data_23.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 30
  subtaskId: 5
data_24.in:
  timeLimit: 5000
  memoryLimit: 512000
  score: 30
  subtaskId: 5